# Generated by Django 5.0.6 on 2024-06-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='date_of_birth',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
    ]
