# Generated by Django 5.0.6 on 2024-06-18 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_seller_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='date_of_birth',
            field=models.DateField(auto_now_add=True),
        ),
    ]
